name: 'Publish Package'
on:
    release:
        types:
            - published
jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - {name: 'Checkout Repository', uses: actions/checkout@v1}
            - {name: 'Install Node v12', uses: actions/setup-node@v1, with: {node-version: 12, registry-url: 'https://registry.npmjs.org/'}}
            - {run: 'npm ci'}
            - {run: 'npm publish', env: {NODE_AUTH_TOKEN: '${{secrets.npm_token}}'}}
    publish-gpr:
        runs-on: ubuntu-latest
        steps:
            - {name: 'Checkout Repository', uses: actions/checkout@v1}
            - {name: 'Install Node v12', uses: actions/setup-node@v1, with: {node-version: 12, registry-url: 'https://npm.pkg.github.com/'}}
            - {run: 'npm ci'}
            - {run: 'npm publish', env: {NODE_AUTH_TOKEN: '${{secrets.GITHUB_TOKEN}}'}}
